require("htn.text.divider").add_syntax_highlights()
require("htn.text.header").add_syntax_highlights()
require("htn.text.list").add_syntax_highlights()
require("htn.text.flag").add_syntax_highlights()
require("htn.ui.fold").add_syntax_highlights()
